version: "3.8"

services:
    backend:
        image: node:latest
        container_name: tengja_backend_d
        # restart: always
        ports:
            - "4000:4000"
        working_dir: /usr/home/app
        volumes:
            - ./tengja_backend_d:/usr/home/app
        command: "yarn run start-dev"
        networks:
            - frontend
            - backend
    redis:
        image: redis
        ports: 
            - "6379:6379"
        container_name: tengja_redis_d
        command: ["redis-server", "--appendonly", "yes"]
        privileged: true
        hostname: redis
        networks:
            - backend
        volumes:
            - ./mounts/tengja_redis_d/config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./mounts/tengja_redis_d/scripts:/scripts
        command: bash -c "/scripts/init.sh"
    frontend:
        image: node:latest
        container_name: tengja_frontend_d
        stdin_open: true
        ports:
            - "80:3000"
        working_dir: /usr/home/app
        volumes:
            - ./tengja_frontend_d:/usr/home/app
        command: "yarn start"
        networks:
            - frontend

networks: 
    frontend:
    backend: